### PR TITLE
Feature: Individual Member Files

### PR DESCRIPTION
**Pull request by MrKragh**
As the member page is becoming quite long and hard to maintain, I recommend splitting this up to individual files.

This is allowing to see when a members "profile" was last updated (can see some really old and incorrect data in between) and giving them unique numbers for sorting.

Unfortunately Jekyll Liquid handles the file numbers as string and therefore sorting is broken. Giving them id's within each file is how the sorting is done, rather than having files with a 4 digit sequence number 0001, 0002, 0003, etc.

I've included a `_.template` file for new members to use and just fill out accordingly. Note, I currently doesn't handle blank values nicely, therefore I recommend to remove the fields not being used.

### CODE REVIEW

**Comment by kbodeholt** [comment]
Thank you for your contribution, Kevin! I'm glad to see VSec members helping with the different projects and the site!
May I feature you on the contributor page?

https://github.com/VSecDK/vsec.dk/blob/main/_pages/contributing.md

**Review by kbodeholt — APPROVED** [review]
Commit reviewed and approved for merge into main.

**Review by kbodeholt — APPROVED** [review]
Commit reviewed and approved for merge into main.

**Review by kbodeholt — APPROVED** [review]
Commit reviewed and approved for merge into main.
Maybe mastodon should be rename "fediverse" to include links to future fediverse networks like "threads" such as https://www.threads.net/@kbodeholt

**Comment by MrKragh** [comment]
First seeing this now, sorry! I just had another project with Jekyll and felt like actually doing something good for the community and learning some more Jekyll along the way.

I'm unfortunately first now seeing how github-pages doesn't render the profiles as my local environment. Will have to do some more testing and eventually come back with a new PR. Example from my local build.

image

> Thank you for your contribution, Kevin! I'm glad to see VSec members helping with the different projects and the site! May I feature you on the contributor page?
> 
> https://github.com/VSecDK/vsec.dk/blob/main/_pages/contributing.md

Of course, thank you for mentioning this!


> Commit reviewed and approved for merge into main. Maybe mastodon should be rename "fediverse" to include links to future fediverse networks like "threads" such as https://www.threads.net/@kbodeholt

It will be easy to do, currently only two "profiles" using the mastodon key, and currently just expecting it to be `user@server.domain` and rewriting that to be the url. Maybe I should add comments to the template with examples of each?

**Comment by kbodeholt** [comment]
No need to be sorry @MrKragh I'm only glad that people like you contributes to the community!
Looking forward to the new PR I think your picture saves more space than the current PR, so that would just be great.
Feel free to add the fediverse key change and whatever you else would like to add, comments in the template would also be nice for people not that experience with git and markdown. Will add you to the contribution page.

**Pull request merged**
